// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetDotNet.Data;

#nullable disable

namespace ProjetDotNet.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250128211540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ProjetDotNet.Models.FileCollectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCollectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCollectionId");

                    b.ToTable("FileCollections");
                });

            modelBuilder.Entity("ProjetDotNet.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileCollectionModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileCollectionModelId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ProjetDotNet.Models.FileCollectionModel", b =>
                {
                    b.HasOne("ProjetDotNet.Models.FileCollectionModel", "ParentCollection")
                        .WithMany("SubCollections")
                        .HasForeignKey("ParentCollectionId");

                    b.Navigation("ParentCollection");
                });

            modelBuilder.Entity("ProjetDotNet.Models.FileModel", b =>
                {
                    b.HasOne("ProjetDotNet.Models.FileCollectionModel", null)
                        .WithMany("Files")
                        .HasForeignKey("FileCollectionModelId");
                });

            modelBuilder.Entity("ProjetDotNet.Models.FileCollectionModel", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("SubCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
